import streamlit as st
import pandas as pd
import numpy as np
import re
import math
from matplotlib import colormaps
import plotly.express as px
import plotly.graph_objects as go
from utils import custom_widgets as cw

import warnings
warnings.filterwarnings("ignore")

@st.cache_data
def read_data(available_years, startgroups, control_points, sortorder):
    
    # Merge all parquets
    df_full = pd.concat([pd.read_parquet(f"data/{year}_full.parquet") for year in available_years], ignore_index=True)
    #tmp.columns = ['placement', 'placement_gender', 'startnr', 'name', 'name_startnr','name_startnr_year', 'class', 'club', 'time', 'gender',
    #   'control', 'year', 'country', 'duration_s', 'duration_h', 'duration_m', 'startgroup','startgroup_year',
    #   'd_duration_s', 'd_duration_m', 'height_m', 'distance_km', 'd_distance_km', 'd_ascent',
    #   'd_descent', 'avg_speed_kmh', 'avg_speed_minkm']

    # Typecasting
    for col in ["placement", "placement_gender", "year", "duration_s", "duration_m", "duration_h", "d_duration_s", "d_duration_m","height_m",
            "distance_km", "d_distance_km", "d_ascent", "d_descent", "avg_speed_kmh", "avg_speed_minkm"]:
        df_full[col] = pd.to_numeric(df_full[col])


    for col in ["class", "club", "gender", "country"]:
        df_full[col] = df_full[col].astype("category")

    
    df_full["startgroup"] = pd.Categorical(df_full["startgroup"], categories=startgroups, ordered=True)

    
    df_full["control"] = pd.Categorical(df_full["control"], categories=sortorder, ordered=True)

    for col in ["startnr", "name", "name_startnr"]:
        df_full[col] = df_full[col].astype("string")
    
    return df_full



# Page setting
st.set_page_config(layout="wide", page_title="VasaData - Vasaloppet Results")

plotly_config = {'displayModeBar': False, 'scrollZoom':False }

with open('style.css') as f:
    st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)

# Data load & data management
available_years = [2018, 2019, 2020, 2022, 2023, 2024, 2025, 2026]
startgroups = ["Elit","1","2","3","4","5","6","7","8","9","10"]
control_points = ["Start", "Smågan", "Mångsbodarna", "Risberg", "Evertsberg", "Oxberg", "Hökberg", "Eldris", "Finish"]
sortorder = ["Start", "High Point", "Smågan", "Mångsbodarna", "Risberg", "Evertsberg", "Oxberg", "Hökberg", "Eldris", "Finish"]

# Vasaloppet.TV checkpoint webcam URLs per year
# These link to the fixed camera recordings at each checkpoint on vasaloppet.tv
webcam_urls = {
    2026: {
        "Start": "https://vasaloppet.tv/video/1115868/vlstsa2026/",
        "Smågan": "https://vasaloppet.tv/video/1115876/vlsm2026/",
        "Mångsbodarna": "https://vasaloppet.tv/video/1115880/vlma2026/",
        "Evertsberg": "https://vasaloppet.tv/video/1115888/vlev2026/",
        "Oxberg": "https://vasaloppet.tv/video/1115892/vlox2026/",
        "Hökberg": "https://vasaloppet.tv/video/1115896/vlho2026/",
        "Eldris": "https://vasaloppet.tv/video/1115900/vlel2026/",
        "Finish": "https://vasaloppet.tv/video/1115904/vlmo2026/",
    },
    2025: {
        "High Point": "https://vasaloppet.tv/video/1114595/hogsta-punkten-vasaloppet-2025/",
        "Smågan": "https://vasaloppet.tv/video/1114600/smagan-vasaloppet-2025/",
        "Risberg": "https://vasaloppet.tv/video/1114610/risberg-vasaloppet-2025/",
        "Evertsberg": "https://vasaloppet.tv/video/1114615/evertsberg-vasaloppet-2025/",
        "Oxberg": "https://vasaloppet.tv/video/1114620/oxberg-vasaloppet-2025/",
        "Hökberg": "https://vasaloppet.tv/video/1114625/hokberg-vasaloppet-2025/",
        "Eldris": "https://vasaloppet.tv/video/1114630/eldris-vasaloppet-2025/",
    },
    2024: {
        "Smågan": "https://vasaloppet.tv/video/1113422/smagan-vasaloppet-2024/",
        "Finish": "https://vasaloppet.tv/video/1113437/malgang-i-mora-vasaloppet-2024/",
    },
}

if 'data' not in st.session_state:
    st.session_state['data'] = read_data(available_years=available_years, startgroups=startgroups, control_points=control_points, sortorder=sortorder)

df_full = st.session_state['data']

### ---------------------- Start of Page -----------------------
# Calculations
# Layout
st.title("VasaData - Vasaloppet Results")
st.write("""Welcome to an interactive analysis app of the Vasaloppet results! \n
The data in this app is generated by the result lists from Vasaloppet but the app is not related to the Official Vasaloppet Organization in any way.

    Comments: 
        - Distance and speeds are caluclated from GPS track distance, not Vasaloppet official control distances.
        - This app is not endorsed or sponsored by Vasaloppet, but was built as a hobby project. If you like it, please share it and give a like :)!
        - If you have an idea, want to give feedback or just say you enjoy the app, please write a comment at https://www.skidforum.se/topic/15964-webapp-f%C3%B6r-analys-av-vasaloppsresultat/!
        - Now also updated with 2025 data. Big thanks also to the great crowd at IK Stern for nice feedback and comments, you know who you are :D! 
        - By popular demand, added a new feature to add multiple years of your or others results at the bottom, to analyze your performance year over year.
        - Added 2026 data and updated some linguistics. 2026-03-01
        - Re-Added 2026 data to get the final participants enjoying the extended rope times. Memory tweaks and addition of sections to make the app more stable and faster. 2026-03-02

""")

st.divider()

### ---------------------- General Information  -----------------------
# Pickers and Headers.
st.header("General Information: ")

year = st.selectbox("Pick Year", available_years, index=len(available_years)-1)
df = df_full[df_full.year==year].copy()

if year<2022:
    first_controlpoint = "Smågan"
else:
    first_controlpoint = "High Point"

# Calculations

@st.cache_data
def grp_row(first_controlpoint):
    return df.loc[df.control==first_controlpoint, ["startnr", "startgroup"]].groupby("startgroup").count().reindex(startgroups)

start_participants = len(df.startnr.unique())
females = len(df[df.gender=="W"].startnr.unique())
males = len(df[df.gender=="M"].startnr.unique())
grp_row = grp_row(first_controlpoint)
df_finish = df[df.control=="Finish"]
df_finish["medal"] =  0
df_finish.loc[(df_finish.gender=="M") & (df_finish.duration_s<=(df_finish[df_finish.gender=="M"].duration_s.min()*1.5)), "medal"] = 1
df_finish.loc[(df_finish.gender=="W") & (df_finish.duration_s<=(df_finish[df_finish.gender=="W"].duration_s.min()*1.5)), "medal"] = 1
female_medalists = df_finish[df_finish.gender=="W"].medal.sum()
male_medalists = df_finish[df_finish.gender=="M"].medal.sum()
df_finish_medal = df_finish[["startgroup", "medal"]].groupby(by="startgroup").sum().reset_index()

# Data Contents Layout
cols = st.columns(5)
with cols[0]:
    cw.number_card(start_participants, "Total Participants")
with cols[1]:
    cw.number_card_tworow(males, str(round(100 * males / start_participants, 1)) + "%",
                          "Male Participants")
with cols[2]:
    cw.number_card_tworow(male_medalists, str(round(100 * male_medalists / males, 1)) + "%",
                          "Male Medalists (1.5x winning time)")
with cols[3]:
    cw.number_card_tworow(females, str(round(100 * females / start_participants, 1)) + "%",
                          "Female Participants")
with cols[4]:
    cw.number_card_tworow(female_medalists, str(round(100 * female_medalists / females, 1)) + "%",
                          "Female Medalists (1.5x winning time)")

cols = st.columns(2)
with cols[0]:
    fig = px.histogram(df_finish, x="duration_h", title="Total Finish time distribution",
                       labels={'duration_h': 'Duration Hours', 'count': '# Participants'},
                       color_discrete_sequence=px.colors.qualitative.Set3)

    fig.update_traces(xbins=dict(start=3.5, end=13.5, size=0.5))

    st.plotly_chart(fig, width='stretch', config=plotly_config)

    st.write("""Histogram showing the distibution of finish times of all participants in blocks of 30mins.
                      I.e. the bar at 6-6.5h shows the amount of participants finishing the race in 6-6.5 hours """)
with cols[1]:
    fig = px.scatter(df_finish, y="placement_gender", x="duration_h", color="gender",
                               title="Placement vs Finish Time",
                               labels={'duration_h': 'Duration Hours', 'placement_gender': 'Placement'},
                    color_discrete_sequence=px.colors.qualitative.Set3)
    st.plotly_chart(fig, width='stretch', config=plotly_config)


    st.write("""Plot showing the relationship between finish time and position in the race for men and women.
                  Hover over the plots x-axis to see what a certain time would have given you as a placement (y-axis) """)

cols = st.columns(2)
with cols[0]:
    fig = px.bar(grp_row, x=grp_row.index, y="startnr",
                title="Participants and Medalists per Start Group",
                labels={'startnr': '# Participants', 'startgroup': 'Row'},barmode='overlay',
                color_discrete_sequence=px.colors.qualitative.Set3)

    fig.add_trace(
        go.Bar(name="Medalists", x=df_finish_medal.startgroup, y=df_finish_medal.medal, marker_color=px.colors.qualitative.Set3[1]))

    fig.update_layout(xaxis_type='category')
    st.plotly_chart(fig, width='stretch', config=plotly_config)
    st.write("""Plot showing number of starting participants at each start-group of vasaloppet, and number of medalists per startgroup (yellow overlay)""")

with cols[1]:
    fig = px.violin(df_finish.sort_values(by="startgroup"), x="startgroup", y="duration_h",
                              title="Finish Time Distribution per Start Group",
                              labels={'duration_h': 'Duration Hours', 'startgroup': 'Row'},
                    color_discrete_sequence=px.colors.qualitative.Set3)

    fig.update_layout(xaxis_type='category')
    st.plotly_chart(fig, width='stretch', config=plotly_config)
    st.write("""Violin-plot showing the finish time distributions per starting group. Where the "violin" is as thickest means that most participants from that start-group finished in that time. 
                Hover over the graph to see more metrics such as the mean time for the start group or the outer quantiles. """)

st.divider()
### ---------------------- Break Offs  -----------------------
# Pickers and Headers.
st.header("DNF Analysis:")

# Calculations



finish_participants = df[df.control=="Finish"].startnr.nunique()
females_finishing = df[(df.control=="Finish")&(df.gender=="W")].startnr.nunique()
males_finishing = df[(df.control=="Finish")&(df.gender=="M")].startnr.nunique()
row_start = df.groupby(by="startgroup").startnr.nunique()
row_finish = df[df.control=="Finish"].groupby(by="startgroup").startnr.nunique()
row_delta = row_start - row_finish

grp = df[(df["control"].isin(control_points))&(df.gender=="W")].groupby(by=["control"]).startnr.count().reindex(control_points)
grp["Start"] = df[df.gender=="W"].startnr.nunique()
female_breaks = -(grp - grp.shift(1))
grp = df[(df["control"].isin(control_points))&(df.gender=="M")].groupby(by=["control"]).startnr.count().reindex(control_points)
grp["Start"] = df[df.gender=="M"].startnr.nunique()
male_breaks = -(grp - grp.shift(1))

df_breaks = pd.DataFrame({"Total":female_breaks+male_breaks,
                        }).reset_index().melt("control")

df_breaks = df_breaks[df_breaks.control.isin(control_points[1:])]

df_breaks_share = pd.DataFrame({"W":100*female_breaks/female_breaks.sum(),
                        "M":100*male_breaks/male_breaks.sum(),
                        }).reset_index().melt("control")
df_breaks_share = df_breaks_share[df_breaks_share.control.isin(control_points[1:])]

df_breaks_row = pd.DataFrame({"Starting":row_start,
                            "DNFs": row_start-row_finish,
                            "DNFs %": round(100*(row_start-row_finish)/row_start,2),
                            "DNFs % of Total": round(100*(row_start-row_finish)/(row_start-row_finish).sum(),2)}).reindex(startgroups).reset_index()

# Data Contents Layout
cols = st.columns(3)
with cols[0]:
    cw.number_card_tworow(start_participants-finish_participants,
                        str(round(100*(start_participants-finish_participants)/start_participants,2))+"%",
                        "Total DNFs")
with cols[1]:
    cw.number_card_tworow(females-females_finishing, str(round(100*(females-females_finishing)/females,2)) + "%",
                        "Female DNFs")
with cols[2]:
    cw.number_card_tworow(males - males_finishing,
                        str(round(100 * (males - males_finishing) / males, 2)) + "%",
                        "Male DNFs")
cols = st.columns(2)
with cols[0]:
    fig = px.bar(df_breaks, x="control", y="value",
                        labels={'value': '# DNFs', 'control': 'Controlpoint'},
                        title="# DNFs before Controlpoint",
                    color_discrete_sequence=px.colors.qualitative.Set3)
    st.plotly_chart(fig, width='stretch', config=plotly_config)
    st.write("""Showing the amount of participants that aborted the race before a certain control-point. 
    I.e. the value at Mångsbodarna shows how many participants that reached Smågan, but did not reach  (could have gotten stuck in the rope in Smågan, as the rope gets pulled after the timing-station)""")
with cols[1]:
    fig = px.bar(df_breaks_share, x="control", y="value", barmode="group", color="variable",
                        labels={'value': '% of DNFs', 'control': 'Controlpoint'},
                        title="DNF Distribution per Gender",
                    color_discrete_sequence=px.colors.qualitative.Set3)
    st.plotly_chart(fig, width='stretch', config=plotly_config)
    st.write("""Showing the distribution between the control points of the aborted races per participants and per gender. 
    I.e. you can see if a certain gender is more or less likely to abort early vs late in the race for example.""")

cols = st.columns(2)
with cols[0]:
    fig = px.bar(df_breaks_row,
                x="startgroup",
                y="DNFs",
                title="Total Number of DNFs per Startrow",
                labels={'DNFs': '# of DNFs', 'startgroup': 'Row'},
                    color_discrete_sequence=px.colors.qualitative.Set3)
    fig.update_layout(xaxis_type='category')
    st.plotly_chart(fig, width='stretch', config=plotly_config)
    st.write("""Showing the total number of DNFs per start-row""")
with cols[1]:
    fig = px.bar(df_breaks_row,
                x="startgroup",
                y="DNFs %",
                title="DNF Share per Startrow",
                labels={"DNFs %": "% Share of Startgroup Participants", 'startgroup': 'Row'},
                    color_discrete_sequence=px.colors.qualitative.Set3)
    fig.update_layout(xaxis_type='category')
    st.plotly_chart(fig, width='stretch', config=plotly_config)
    st.write("""Showing the DNFs as a share of number of participants in that start-row""")

st.divider()

### ---------------------- Section Analysis  -----------------------
# Pickers and Headers.
st.header("Section, High Point & Overtake Analysis:")

df_speed = df.loc[df.avg_speed_kmh<40,["control","startgroup", "avg_speed_kmh"]].groupby(by=["control","startgroup"]).mean().reset_index()
df_speed_gender = df.loc[df.avg_speed_kmh<40,["control","gender", "avg_speed_kmh"]].groupby(by=["control","gender"]).mean().reset_index()

cols = st.columns(2)
with cols[0]:
    fig = px.line(df_speed[df_speed.control != "Start"], x="control", y="avg_speed_kmh",
                color="startgroup", title='Average Speed per Section and Startgroup',
                labels={"avg_speed_kmh": "km/h (avg)", 'control': 'Controlpoint'},
                    color_discrete_sequence=px.colors.qualitative.Set3)
    st.plotly_chart(fig, width='stretch', config=plotly_config)
    st.write("""Showing the average speed per section and start group. Note that it is the average speed on the section
    up to the control, so the linegraph at Smågan shows the average speed between High Point and Smågan.""")

with cols[1]:
    fig = px.violin(df[df.control==first_controlpoint].sort_values(by="startgroup"), x="startgroup", y="duration_m",
                                title=f'Time to reach {first_controlpoint} per Start Row',
                                labels={'duration_m': 'Duration Minutes', 'startgroup': 'Row'},
                    color_discrete_sequence=px.colors.qualitative.Set3)
    fig.update_layout(xaxis_type='category')
    st.plotly_chart(fig, width='stretch', config=plotly_config)
    st.write(f'Violin-plot showing the time distribution to reach {first_controlpoint}, from different start-groups.')

cols = st.columns(2)
with cols[1]:
    places = pd.merge(df.loc[df.control=="Finish", ["name_startnr","startgroup", "placement", "placement_gender"]],
                    df.loc[df.control==first_controlpoint, ["name_startnr", "placement", "placement_gender"]],
                    how='left', on='name_startnr')
    places["delta_placements"] = (places.placement_y - places.placement_x)
    places["delta_placements_gender"] = (places.placement_gender_y - places.placement_gender_x)
    places = places.sort_values(by="delta_placements", ascending=False).reset_index()
    places = places[["name_startnr","startgroup", "placement_x", "delta_placements", "delta_placements_gender"]]
    places.columns = ["Name (startnr)","Startgroup", "Final Placement", "Places Gained/Lost", "Places Gained/Lost Gender"]
    st.write("#### Places Gained/Lost")
    st.write(places)
    st.write("""Utilize the headers to re-sort the graph to look at most places gained/lost. A positive number means position improvement
    If you hover over the table, a search icon will appear in the top right where you can search for specific individuals""")

with cols[0]:
    df_speed_gender = df.loc[df.avg_speed_kmh < 40, ["control", "gender", "avg_speed_kmh"]].groupby(by=["control", "gender"]).mean().reset_index()

    fig = px.line(df_speed_gender[(df_speed_gender.control != "Start")], x="control", y="avg_speed_kmh",
                color="gender", title='Average Speed per Section and Gender',
                labels={"avg_speed_kmh": "km/h (avg)", 'control': 'Controlpoint'},
                    color_discrete_sequence=px.colors.qualitative.Set3)
    st.plotly_chart(fig, width='stretch', config=plotly_config)
    st.write("""Showing the average speed per section and Gender. Note that it is the average speed on the section
    up to the control, so the linegraph at Smågan shows the average speed between High Point and Smågan.""")

st.divider()
### ---------------------- Individual Comparison  -----------------------
# Pickers and Headers.
st.header("Individual Participant Results Analysis:")

cols = st.columns(2)

df_avg_startgroup = df.loc[(df.avg_speed_kmh<40)&(df.control!="Start"),["control","startgroup", "avg_speed_kmh", "d_duration_m", "placement"]].groupby(by=["control","startgroup"]).mean().reset_index()

with cols[0]:
    selected_names = st.multiselect('Add names that you want to analyse and/or compare', df.name_startnr.unique())
with cols[1]:
    selected_groups = st.multiselect('Add Startgroup averages as comparisons', df.startgroup.unique().sort_values())


cols = st.columns(2)
with cols[0]:
    fig = px.line(df[(df.control != "Start") & (df.name_startnr.isin(selected_names))], x="control", y="avg_speed_kmh",
                    color="name", title='Average Speed per Section',
                    labels={"avg_speed_kmh": "km/h (avg)", 'control': 'Controlpoint'},
                        color_discrete_sequence=px.colors.qualitative.Set3)

    for i, group in enumerate(selected_groups):
        tmp = df_avg_startgroup[(df_avg_startgroup.startgroup==group) & (df_avg_startgroup.control!="Start")]
        fig.add_trace(go.Scatter(x=tmp.control, y=tmp.avg_speed_kmh, name=group,
                                line=dict(width=2, dash='dot', color=px.colors.qualitative.Prism[i])))

    fig.update_layout(xaxis_type='category')
    st.plotly_chart(fig, width='stretch', config=plotly_config)

with cols[1]:
    fig = px.bar(df[(df.control != "Start") & (df.name_startnr.isin(selected_names))], x="control", y="d_duration_m",
                color="name", title='Average Duration per Section',barmode="group",
                labels={"d_duration_m": "Duration Minutes", 'control': 'Controlpoint'}, range_y=[0,180],
                color_discrete_sequence=px.colors.qualitative.Set3)

    for i, group in enumerate(selected_groups):
        tmp = df_avg_startgroup[(df_avg_startgroup.startgroup==group) & (df_avg_startgroup.control!="Start")]
        fig.add_trace(go.Scatter(x=tmp.control, y=tmp.d_duration_m, name=group,
                                line=dict(width=2, dash='dot', color=px.colors.qualitative.Prism[i])))

    st.plotly_chart(fig, width='stretch', config=plotly_config)

# Add Placement Information
with cols[0]:
    fig = px.line(df[(df.control != "Start") & (df.name_startnr.isin(selected_names))], x="control", y="placement",
                    color="name", title='Total Placement per Control',
                    labels={"placement": "Placement", 'control': 'Controlpoint'},
                        color_discrete_sequence=px.colors.qualitative.Set3)

    for i, group in enumerate(selected_groups):
        tmp = df_avg_startgroup[(df_avg_startgroup.startgroup==group) & (df_avg_startgroup.control!="Start")]
        fig.add_trace(go.Scatter(x=tmp.control, y=tmp.placement, name=group,
                                line=dict(width=2, dash='dot', color=px.colors.qualitative.Prism[i])))

    st.plotly_chart(fig, width='stretch', config=plotly_config)

with cols[1]:
    st.write("#### Table View of Selected Data")
    st.dataframe(df.loc[(df.control == "Finish") & (df.name_startnr.isin(selected_names)),["name_startnr","startgroup","club", "time", "placement", "placement_gender"]], hide_index=True)

# Webcam correlation section
year_urls = webcam_urls.get(year, {})
if selected_names and year_urls:
    st.write("#### Checkpoint Webcam Correlation")
    st.caption("Watch participants pass each checkpoint on [Vasaloppet.TV](https://vasaloppet.tv). "
               "The approx. clock time helps you scrub to the right moment in the video player (race starts ~08:00, later start groups depart slightly after).")

    for name in selected_names:
        df_person = df[(df.name_startnr == name)].sort_values("control").copy()
        if not df_person.empty:
            df_webcam = df_person[["control", "time", "duration_s"]].copy()
            df_webcam["Clock Time (approx)"] = (
                pd.to_datetime("08:00:00") + pd.to_timedelta(df_webcam["duration_s"], unit="s")
            ).dt.strftime("%H:%M:%S")
            df_webcam["Webcam"] = df_webcam["control"].map(year_urls)
            df_webcam = df_webcam[df_webcam["Webcam"].notna()].copy()
            if not df_webcam.empty:
                display_df = df_webcam[["control", "time", "Clock Time (approx)", "Webcam"]].copy()
                display_df.columns = ["Checkpoint", "Elapsed Time", "Clock Time (approx)", "Webcam"]
                st.write(f"**{name}**")
                st.dataframe(
                    display_df,
                    column_config={
                        "Webcam": st.column_config.LinkColumn("Webcam", display_text="Watch on Vasaloppet.TV"),
                    },
                    hide_index=True,
                )

st.divider()

### ---------------------- Year over Year Comparison  -----------------------
# Pickers and Headers.
st.header("Year over Year Comparison:")

@st.cache_data
def calculate_start_years(df_full):
    return df_full.drop_duplicates(subset=["year", "startnr"])[["year","startgroup","startnr"]].groupby(by=["year", "startgroup"]).count().reset_index()

@st.cache_data
def calculate_breaks_years(df_full):
    df_breaks_year = df_full.drop_duplicates(subset=["year", "startnr"])[["year","startnr"]].groupby(by=["year"]).count()
    df_breaks_year["finish"] = df_full[df_full.control=="Finish"].drop_duplicates(subset=["year", "startnr"])[["year", "startnr"]].groupby(by=["year"]).count()
    df_breaks_year["break_offs"] = df_breaks_year.startnr - df_breaks_year.finish
    return df_breaks_year.reset_index()

df_start_year = calculate_start_years(df_full)
df_breaks_year = calculate_breaks_years(df_full)

cols = st.columns(2)
with cols[0]:
    fig = px.bar(df_start_year, x="year", y="startnr",
                labels={'startnr': '# Participants', 'year': 'Year'},
                title="# Participants per Year (starting)", color="startgroup",
                color_discrete_sequence=px.colors.qualitative.Set3)
    fig.update_layout(xaxis_type='category')
    st.plotly_chart(fig, width='stretch', config=plotly_config)
with cols[1]:
    fig = px.bar(df_breaks_year, x="year", y="break_offs",
                labels={'break_offs': '# DNFs', 'year': 'Year'},
                title="# DNFs per Year",
                color_discrete_sequence=px.colors.qualitative.Set3)
    fig.update_layout(xaxis_type='category')
    st.plotly_chart(fig, width='stretch', config=plotly_config)


cols = st.columns(2)
with cols[0]:
    fig = px.violin(df_full[df_full.control == "Finish"].sort_values(by="year"), x="year", y="duration_h",
                    title="Finish Time Distribution per Year",
                    labels={'duration_h': 'Duration Hours', 'year': 'Year'},
                    color_discrete_sequence=px.colors.qualitative.Set3)
    fig.update_layout(xaxis_type='category')
    st.plotly_chart(fig, width='stretch', config=plotly_config)

with cols[1]:
    fig = px.scatter(df_full[df_full.control=="Finish"], y="placement", x="duration_h", color="year",
                    title="Placement vs Finish Time per Year",
                    labels={'duration_h': 'Duration Hours', 'placement': 'Placement'},
                    color_continuous_scale=px.colors.sequential.YlGnBu)

    st.plotly_chart(fig, width='stretch', config=plotly_config)

# --- Start Group Flow (Sankey) ---
st.write("#### Start Group Flow Between Years")
st.caption("Shows how returning participants moved between start groups from one year to the next — like a user-flow in web analytics.")

# Seeding thresholds (max finish time to qualify for each start group)
seeding_thresholds = {
    2027: {
        "Elit": "4:34:04", "1": "5:12:40", "2": "5:42:04", "3": "6:44:54",
        "4": "7:51:38", "5": "8:47:09", "6": "9:33:34", "7": "10:22:03",
        "8": "11:31:38", "9": "13:23:00",
    },
}

@st.cache_data
def compute_startgroup_flow(df_full, year_from, year_to, sg_order):
    """Count how many returning participants moved between start groups."""
    df_p = df_full.drop_duplicates(subset=["year", "name"])[["year", "name", "startgroup"]]
    df_from = df_p[df_p.year == year_from][["name", "startgroup"]].rename(columns={"startgroup": "sg_from"})
    df_to = df_p[df_p.year == year_to][["name", "startgroup"]].rename(columns={"startgroup": "sg_to"})
    df_flow = df_from.merge(df_to, on="name")
    flow_counts = df_flow.groupby(["sg_from", "sg_to"]).size().reset_index(name="count")
    # Filter to known start groups
    flow_counts = flow_counts[flow_counts.sg_from.isin(sg_order) & flow_counts.sg_to.isin(sg_order)]
    return flow_counts

years_sorted = sorted(df_full.year.unique())
year_pairs = [(years_sorted[i], years_sorted[i + 1]) for i in range(len(years_sorted) - 1)]

sankey_cols = st.columns([1, 3])
with sankey_cols[0]:
    selected_pair = st.selectbox(
        "Year transition",
        year_pairs,
        index=len(year_pairs) - 1,
        format_func=lambda x: f"{x[0]} → {x[1]}",
    )
    show_seeding = False
    if selected_pair[1] in seeding_thresholds:
        show_seeding = st.checkbox("Show seeding thresholds", value=True)
        if show_seeding:
            st.write(f"**Seeding for {selected_pair[1]}**")
            seed_df = pd.DataFrame(
                [(sg, t) for sg, t in seeding_thresholds[selected_pair[1]].items()],
                columns=["Group", "Max Finish Time"],
            )
            st.dataframe(seed_df, hide_index=True, height=390)

sg_order = [sg for sg in startgroups if sg in df_full.startgroup.cat.categories]
flow_counts = compute_startgroup_flow(df_full, selected_pair[0], selected_pair[1], sg_order)

if not flow_counts.empty:
    # Build Sankey nodes: left side = "2024 Elit", right side = "2025 Elit", etc.
    left_labels = [f"{selected_pair[0]} {sg}" for sg in sg_order]
    right_labels = [f"{selected_pair[1]} {sg}" for sg in sg_order]
    all_labels = left_labels + right_labels

    sg_to_left_idx = {sg: i for i, sg in enumerate(sg_order)}
    sg_to_right_idx = {sg: i + len(sg_order) for i, sg in enumerate(sg_order)}

    colors = px.colors.qualitative.Set3
    node_colors = [colors[i % len(colors)] for i in range(len(all_labels))]

    sources, targets, values, link_colors = [], [], [], []
    for _, row in flow_counts.iterrows():
        src = sg_to_left_idx.get(row.sg_from)
        tgt = sg_to_right_idx.get(row.sg_to)
        if src is not None and tgt is not None:
            sources.append(src)
            targets.append(tgt)
            values.append(row["count"])
            # Colour the link by the source group, with transparency
            c = colors[src % len(colors)]
            if c.startswith("rgb("):
                r, g, b = [int(x) for x in c[4:-1].split(",")]
            else:
                base = c.lstrip("#")
                r, g, b = int(base[:2], 16), int(base[2:4], 16), int(base[4:6], 16)
            link_colors.append(f"rgba({r},{g},{b},0.35)")

    fig = go.Figure(go.Sankey(
        node=dict(pad=15, thickness=20, label=all_labels, color=node_colors),
        link=dict(source=sources, target=targets, value=values, color=link_colors),
    ))
    fig.update_layout(
        title_text=f"Start Group Flow: {selected_pair[0]} → {selected_pair[1]}",
        font_size=12,
        height=500,
    )

    with sankey_cols[1]:
        st.plotly_chart(fig, use_container_width=True, config=plotly_config)
else:
    with sankey_cols[1]:
        st.info("No returning participants found between these years.")

# Breakdown table: select a source start group and see where they ended up
if not flow_counts.empty:
    st.write("#### Start Group Breakdown")
    breakdown_cols = st.columns([1, 3])
    with breakdown_cols[0]:
        available_sgs = sorted(flow_counts.sg_from.unique(), key=lambda x: sg_order.index(x) if x in sg_order else 99)
        selected_sg = st.selectbox(
            f"Source start group ({selected_pair[0]})",
            available_sgs,
            format_func=lambda x: f"Group {x}" if x != "Elit" else "Elit",
        )

    sg_data = flow_counts[flow_counts.sg_from == selected_sg].copy()
    total = sg_data["count"].sum()
    sg_data["Percentage"] = (sg_data["count"] / total * 100).round(1)
    sg_data = sg_data.sort_values("sg_to", key=lambda s: s.map({sg: i for i, sg in enumerate(sg_order)}))
    sg_data = sg_data.rename(columns={"sg_to": f"Start Group {selected_pair[1]}", "count": "Participants"})
    sg_data = sg_data[[f"Start Group {selected_pair[1]}", "Participants", "Percentage"]].reset_index(drop=True)
    sg_data["Percentage"] = sg_data["Percentage"].apply(lambda x: f"{x}%")

    with breakdown_cols[1]:
        st.caption(f"**{total}** returning participants from group **{selected_sg}** in {selected_pair[0]}")
        st.dataframe(sg_data, hide_index=True, use_container_width=True)

# Seeding projection: given a start group's finish times, show projected next-year seeding
def _time_to_seconds(t):
    """Convert H:MM:SS or HH:MM:SS string to seconds."""
    parts = t.split(":")
    return int(parts[0]) * 3600 + int(parts[1]) * 60 + int(parts[2])

# Find which seeding table applies to the "from" year (i.e. from_year finish → from_year+1 seeding)
seeding_target_year = selected_pair[0] + 1
if seeding_target_year in seeding_thresholds:
    st.write("#### Projected Seeding from Finish Times")
    st.caption(f"Based on {selected_pair[0]} finish times and {seeding_target_year} seeding thresholds — where would each start group be seeded next year?")

    # Build ordered thresholds in seconds
    seed_order = [sg for sg in sg_order if sg in seeding_thresholds[seeding_target_year]]
    seed_limits = [(sg, _time_to_seconds(seeding_thresholds[seeding_target_year][sg])) for sg in seed_order]

    def classify_seeding(duration_s):
        for sg, limit in seed_limits:
            if duration_s <= limit:
                return sg
        return "10+"

    # Get finishers from the "from" year
    df_finishers = df_full[(df_full.year == selected_pair[0]) & (df_full.control == "Finish")].copy()

    seed_cols = st.columns([1, 3])
    with seed_cols[0]:
        available_sgs_seed = sorted(
            df_finishers.startgroup.unique(),
            key=lambda x: sg_order.index(x) if x in sg_order else 99,
        )
        selected_sg_seed = st.selectbox(
            f"Start group in {selected_pair[0]}",
            available_sgs_seed,
            format_func=lambda x: f"Group {x}" if x != "Elit" else "Elit",
            key="seeding_sg",
        )

    df_sg = df_finishers[df_finishers.startgroup == selected_sg_seed].copy()
    df_sg["Projected Group"] = df_sg.duration_s.apply(classify_seeding)

    seed_counts = df_sg.groupby("Projected Group").size().reset_index(name="Participants")
    # Sort by startgroup order
    all_groups = seed_order + ["10+"]
    seed_counts["_sort"] = seed_counts["Projected Group"].map({sg: i for i, sg in enumerate(all_groups)})
    seed_counts = seed_counts.sort_values("_sort").drop(columns="_sort")
    total_seed = seed_counts["Participants"].sum()
    seed_counts["Percentage"] = (seed_counts["Participants"] / total_seed * 100).round(1).apply(lambda x: f"{x}%")

    with seed_cols[1]:
        st.caption(f"**{total_seed}** finishers from group **{selected_sg_seed}** in {selected_pair[0]} → projected {seeding_target_year} seeding")
        st.dataframe(seed_counts, hide_index=True, use_container_width=True)

st.divider()
## Individual Year over Year Analysis
# Pickers and Headers.
st.header("Individual Results Year over Year Analysis:")

cols = st.columns(2)

@st.cache_data
def df_avg_startgroup_year(df_full):
    return df_full.loc[(df_full.avg_speed_kmh<40)&(df_full.control!="Start"),["control","startgroup_year", "avg_speed_kmh", "d_duration_m", "placement"]].groupby(by=["control","startgroup_year"]).mean().reset_index()

df_full_avg_startgroup = df_avg_startgroup_year(df_full)

with cols[0]:
    selected_names_year = st.multiselect('Add names and years to analyse and/or compare', df_full.name_startnr_year.unique())
with cols[1]:
    selected_groups_year = st.multiselect('Add yearly startgroup averages as comparisons', df_full.startgroup_year.sort_values().unique())


cols = st.columns(2)
with cols[0]:
    fig = px.line(df_full[(df_full.control != "Start") & (df_full.name_startnr_year.isin(selected_names_year))], x="control", y="avg_speed_kmh",
                    color="name_startnr_year", title='Average Speed per Section and Year',
                    labels={"avg_speed_kmh": "km/h (avg)", 'control': 'Controlpoint'},
                        color_discrete_sequence=px.colors.qualitative.Set3)

    for i, group in enumerate(selected_groups_year):
        tmp = df_full_avg_startgroup[(df_full_avg_startgroup.startgroup_year==group) & (df_full_avg_startgroup.control!="Start")]
        fig.add_trace(go.Scatter(x=tmp.control, y=tmp.avg_speed_kmh, name=group,
                                line=dict(width=2, dash='dot', color=px.colors.qualitative.Prism[i])))

    fig.update_layout(xaxis_type='category')
    fig.update_xaxes(categoryorder='array',
                    categoryarray=sortorder)
    st.plotly_chart(fig, width='stretch', config=plotly_config)

with cols[1]:
    fig = px.bar(df_full[(df_full.control != "Start") & (df_full.name_startnr_year.isin(selected_names_year))], x="control", y="d_duration_m",
                color="name_startnr_year", title='Average Duration per Section and Year',barmode="group",
                labels={"d_duration_m": "Duration Minutes", 'control': 'Controlpoint'}, range_y=[0,180],
                color_discrete_sequence=px.colors.qualitative.Set3)

    for i, group in enumerate(selected_groups_year):
        tmp = df_full_avg_startgroup[(df_full_avg_startgroup.startgroup_year==group) & (df_full_avg_startgroup.control!="Start")]
        fig.add_trace(go.Scatter(x=tmp.control, y=tmp.d_duration_m, name=group,
                                line=dict(width=2, dash='dot', color=px.colors.qualitative.Prism[i])))

    fig.update_xaxes(categoryorder='array',
                    categoryarray=sortorder)
    st.plotly_chart(fig, width='stretch', config=plotly_config)

# Add Placement Information
with cols[0]:
    fig = px.line(df_full[(df_full.control != "Start") & (df_full.name_startnr_year.isin(selected_names_year))], x="control", y="placement",
                    color="name_startnr_year", title='Total Placement per Control and Year',
                    labels={"placement": "Placement", 'control': 'Controlpoint'},
                        color_discrete_sequence=px.colors.qualitative.Set3)

    for i, group in enumerate(selected_groups_year):
        tmp = df_full_avg_startgroup[(df_full_avg_startgroup.startgroup_year==group) & (df_full_avg_startgroup.control!="Start")]
        fig.add_trace(go.Scatter(x=tmp.control, y=tmp.placement, name=group,
                                line=dict(width=2, dash='dot', color=px.colors.qualitative.Prism[i])))

    fig.update_xaxes(categoryorder='array',
                    categoryarray=sortorder)
    st.plotly_chart(fig, width='stretch', config=plotly_config)

with cols[1]:
    st.write("#### Table View of Selected Data and Year")
    st.dataframe(df_full.loc[(df_full.control == "Finish") & (df_full.name_startnr_year.isin(selected_names_year)),["name_startnr_year","startgroup_year","club", "time", "placement", "placement_gender"]], hide_index=True)

st.divider()
